django.core.exceptions
======================

.. py:module:: django.core.exceptions

.. autoapi-nested-parse::

   Global Django exception and warning classes.



Attributes
----------

.. autoapisummary::

   django.core.exceptions.NON_FIELD_ERRORS


Exceptions
----------

.. autoapisummary::

   django.core.exceptions.FieldDoesNotExist
   django.core.exceptions.AppRegistryNotReady
   django.core.exceptions.ObjectDoesNotExist
   django.core.exceptions.MultipleObjectsReturned
   django.core.exceptions.SuspiciousOperation
   django.core.exceptions.SuspiciousMultipartForm
   django.core.exceptions.SuspiciousFileOperation
   django.core.exceptions.DisallowedHost
   django.core.exceptions.DisallowedRedirect
   django.core.exceptions.TooManyFieldsSent
   django.core.exceptions.TooManyFilesSent
   django.core.exceptions.RequestDataTooBig
   django.core.exceptions.RequestAborted
   django.core.exceptions.BadRequest
   django.core.exceptions.PermissionDenied
   django.core.exceptions.ViewDoesNotExist
   django.core.exceptions.MiddlewareNotUsed
   django.core.exceptions.ImproperlyConfigured
   django.core.exceptions.FieldError
   django.core.exceptions.ValidationError
   django.core.exceptions.EmptyResultSet
   django.core.exceptions.FullResultSet
   django.core.exceptions.SynchronousOnlyOperation


Module Contents
---------------

.. py:exception:: FieldDoesNotExist

   Bases: :py:obj:`Exception`


   The requested model field does not exist


.. py:exception:: AppRegistryNotReady

   Bases: :py:obj:`Exception`


   The django.apps registry is not populated yet


.. py:exception:: ObjectDoesNotExist

   Bases: :py:obj:`Exception`


   The requested object does not exist


   .. py:attribute:: silent_variable_failure
      :value: True



.. py:exception:: MultipleObjectsReturned

   Bases: :py:obj:`Exception`


   The query returned multiple objects when only one was expected.


.. py:exception:: SuspiciousOperation

   Bases: :py:obj:`Exception`


   The user did something suspicious


.. py:exception:: SuspiciousMultipartForm

   Bases: :py:obj:`SuspiciousOperation`


   Suspect MIME request in multipart form data


.. py:exception:: SuspiciousFileOperation

   Bases: :py:obj:`SuspiciousOperation`


   A Suspicious filesystem operation was attempted


.. py:exception:: DisallowedHost

   Bases: :py:obj:`SuspiciousOperation`


   HTTP_HOST header contains invalid value


.. py:exception:: DisallowedRedirect

   Bases: :py:obj:`SuspiciousOperation`


   Redirect to scheme not in allowed list


.. py:exception:: TooManyFieldsSent

   Bases: :py:obj:`SuspiciousOperation`


   The number of fields in a GET or POST request exceeded
   settings.DATA_UPLOAD_MAX_NUMBER_FIELDS.


.. py:exception:: TooManyFilesSent

   Bases: :py:obj:`SuspiciousOperation`


   The number of fields in a GET or POST request exceeded
   settings.DATA_UPLOAD_MAX_NUMBER_FILES.


.. py:exception:: RequestDataTooBig

   Bases: :py:obj:`SuspiciousOperation`


   The size of the request (excluding any file uploads) exceeded
   settings.DATA_UPLOAD_MAX_MEMORY_SIZE.


.. py:exception:: RequestAborted

   Bases: :py:obj:`Exception`


   The request was closed before it was completed, or timed out.


.. py:exception:: BadRequest

   Bases: :py:obj:`Exception`


   The request is malformed and cannot be processed.


.. py:exception:: PermissionDenied

   Bases: :py:obj:`Exception`


   The user did not have permission to do that


.. py:exception:: ViewDoesNotExist

   Bases: :py:obj:`Exception`


   The requested view does not exist


.. py:exception:: MiddlewareNotUsed

   Bases: :py:obj:`Exception`


   This middleware is not used in this server configuration


.. py:exception:: ImproperlyConfigured

   Bases: :py:obj:`Exception`


   Django is somehow improperly configured


.. py:exception:: FieldError

   Bases: :py:obj:`Exception`


   Some kind of problem with a model field.


.. py:data:: NON_FIELD_ERRORS
   :value: '__all__'


.. py:exception:: ValidationError(message, code=None, params=None)

   Bases: :py:obj:`Exception`


   An error while validating data.


   .. py:property:: message_dict


   .. py:property:: messages


   .. py:method:: update_error_dict(error_dict)


.. py:exception:: EmptyResultSet

   Bases: :py:obj:`Exception`


   A database query predicate is impossible.


.. py:exception:: FullResultSet

   Bases: :py:obj:`Exception`


   A database query predicate is matches everything.


.. py:exception:: SynchronousOnlyOperation

   Bases: :py:obj:`Exception`


   The user tried to call a sync-only function from an async context.


